import type { RequiredDataFromCollectionSlug } from 'payload'
import type { Media, Form } from '@/payload-types'

type AdmissionsArgs = {
  heroImage: Media
  metaImage: Media
  applicationForm: Form
}

export const admissions: (args: AdmissionsArgs) => RequiredDataFromCollectionSlug<'pages'> = ({
  heroImage,
  metaImage,
  applicationForm,
}) => {
  return {
    slug: 'admissions',
    _status: 'published',
    hero: {
      type: 'mediumImpact',
      links: [
        {
          link: {
            type: 'custom',
            appearance: 'default',
            label: 'Start Application',
            url: '/contact',
          },
        },
        {
          link: {
            type: 'custom',
            appearance: 'outline',
            label: 'View Programs',
            url: '/programs',
          },
        },
      ],
      media: heroImage.id,
      richText: {
        root: {
          type: 'root',
          children: [
            {
              type: 'heading',
              children: [
                {
                  type: 'text',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'Admissions',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              tag: 'h1',
              version: 1,
            },
            {
              type: 'paragraph',
              children: [
                {
                  type: 'text',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'Join SDU Institute and start your journey towards a rewarding healthcare career. We offer flexible admission processes and support every step of the way.',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              version: 1,
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          version: 1,
        },
      },
    },
    layout: [
      {
        blockName: 'Admission Requirements',
        blockType: 'content',
        columns: [
          {
            richText: {
              root: {
                type: 'root',
                children: [
                  {
                    type: 'heading',
                    children: [
                      {
                        type: 'text',
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: 'Admission Requirements',
                        version: 1,
                      },
                    ],
                    direction: 'ltr',
                    format: '',
                    indent: 0,
                    tag: 'h2',
                    version: 1,
                  },
                  {
                    type: 'paragraph',
                    children: [
                      {
                        type: 'text',
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: 'We welcome students from diverse academic backgrounds. Our admission requirements are designed to ensure student success while maintaining accessibility.',
                        version: 1,
                      },
                    ],
                    direction: 'ltr',
                    format: '',
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                version: 1,
              },
            },
            size: 'full',
          },
        ],
      },
      {
        blockName: 'Requirements by Program',
        blockType: 'content',
        columns: [
          {
            richText: {
              root: {
                type: 'root',
                children: [
                  {
                    type: 'heading',
                    children: [
                      {
                        type: 'text',
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: 'HND Programs',
                        version: 1,
                      },
                    ],
                    direction: 'ltr',
                    format: '',
                    indent: 0,
                    tag: 'h3',
                    version: 1,
                  },
                  {
                    type: 'list',
                    children: [
                      {
                        type: 'listitem',
                        children: [
                          {
                            type: 'text',
                            detail: 0,
                            format: 0,
                            mode: 'normal',
                            style: '',
                            text: 'GCE A/L with at least 2 passes',
                            version: 1,
                          },
                        ],
                        direction: 'ltr',
                        format: '',
                        indent: 0,
                        version: 1,
                        value: 1,
                      },
                      {
                        type: 'listitem',
                        children: [
                          {
                            type: 'text',
                            detail: 0,
                            format: 0,
                            mode: 'normal',
                            style: '',
                            text: 'Baccalauréat or equivalent',
                            version: 1,
                          },
                        ],
                        direction: 'ltr',
                        format: '',
                        indent: 0,
                        version: 1,
                        value: 2,
                      },
                      {
                        type: 'listitem',
                        children: [
                          {
                            type: 'text',
                            detail: 0,
                            format: 0,
                            mode: 'normal',
                            style: '',
                            text: 'Minimum age of 18 years',
                            version: 1,
                          },
                        ],
                        direction: 'ltr',
                        format: '',
                        indent: 0,
                        version: 1,
                        value: 3,
                      },
                    ],
                    direction: 'ltr',
                    format: '',
                    indent: 0,
                    listType: 'bullet',
                    start: 1,
                    tag: 'ul',
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                version: 1,
              },
            },
            size: 'half',
          },
          {
            richText: {
              root: {
                type: 'root',
                children: [
                  {
                    type: 'heading',
                    children: [
                      {
                        type: 'text',
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: 'BTS/Bachelor Programs',
                        version: 1,
                      },
                    ],
                    direction: 'ltr',
                    format: '',
                    indent: 0,
                    tag: 'h3',
                    version: 1,
                  },
                  {
                    type: 'list',
                    children: [
                      {
                        type: 'listitem',
                        children: [
                          {
                            type: 'text',
                            detail: 0,
                            format: 0,
                            mode: 'normal',
                            style: '',
                            text: 'GCE A/L with at least 2 passes',
                            version: 1,
                          },
                        ],
                        direction: 'ltr',
                        format: '',
                        indent: 0,
                        version: 1,
                        value: 1,
                      },
                      {
                        type: 'listitem',
                        children: [
                          {
                            type: 'text',
                            detail: 0,
                            format: 0,
                            mode: 'normal',
                            style: '',
                            text: 'Baccalauréat or equivalent',
                            version: 1,
                          },
                        ],
                        direction: 'ltr',
                        format: '',
                        indent: 0,
                        version: 1,
                        value: 2,
                      },
                      {
                        type: 'listitem',
                        children: [
                          {
                            type: 'text',
                            detail: 0,
                            format: 0,
                            mode: 'normal',
                            style: '',
                            text: 'HND in related field (for some programs)',
                            version: 1,
                          },
                        ],
                        direction: 'ltr',
                        format: '',
                        indent: 0,
                        version: 1,
                        value: 3,
                      },
                    ],
                    direction: 'ltr',
                    format: '',
                    indent: 0,
                    listType: 'bullet',
                    start: 1,
                    tag: 'ul',
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                version: 1,
              },
            },
            size: 'half',
          },
        ],
      },
      {
        blockName: 'Application Process',
        blockType: 'content',
        columns: [
          {
            richText: {
              root: {
                type: 'root',
                children: [
                  {
                    type: 'heading',
                    children: [
                      {
                        type: 'text',
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: 'How to Apply',
                        version: 1,
                      },
                    ],
                    direction: 'ltr',
                    format: '',
                    indent: 0,
                    tag: 'h2',
                    version: 1,
                  },
                  {
                    type: 'list',
                    children: [
                      {
                        type: 'listitem',
                        children: [
                          {
                            type: 'text',
                            detail: 0,
                            format: 1,
                            mode: 'normal',
                            style: '',
                            text: 'Step 1: ',
                            version: 1,
                          },
                          {
                            type: 'text',
                            detail: 0,
                            format: 0,
                            mode: 'normal',
                            style: '',
                            text: 'Visit any of our campus locations or contact us online',
                            version: 1,
                          },
                        ],
                        direction: 'ltr',
                        format: '',
                        indent: 0,
                        version: 1,
                        value: 1,
                      },
                      {
                        type: 'listitem',
                        children: [
                          {
                            type: 'text',
                            detail: 0,
                            format: 1,
                            mode: 'normal',
                            style: '',
                            text: 'Step 2: ',
                            version: 1,
                          },
                          {
                            type: 'text',
                            detail: 0,
                            format: 0,
                            mode: 'normal',
                            style: '',
                            text: 'Complete the application form and submit required documents',
                            version: 1,
                          },
                        ],
                        direction: 'ltr',
                        format: '',
                        indent: 0,
                        version: 1,
                        value: 2,
                      },
                      {
                        type: 'listitem',
                        children: [
                          {
                            type: 'text',
                            detail: 0,
                            format: 1,
                            mode: 'normal',
                            style: '',
                            text: 'Step 3: ',
                            version: 1,
                          },
                          {
                            type: 'text',
                            detail: 0,
                            format: 0,
                            mode: 'normal',
                            style: '',
                            text: 'Attend an interview (if required for your program)',
                            version: 1,
                          },
                        ],
                        direction: 'ltr',
                        format: '',
                        indent: 0,
                        version: 1,
                        value: 3,
                      },
                      {
                        type: 'listitem',
                        children: [
                          {
                            type: 'text',
                            detail: 0,
                            format: 1,
                            mode: 'normal',
                            style: '',
                            text: 'Step 4: ',
                            version: 1,
                          },
                          {
                            type: 'text',
                            detail: 0,
                            format: 0,
                            mode: 'normal',
                            style: '',
                            text: 'Receive admission decision and complete enrollment',
                            version: 1,
                          },
                        ],
                        direction: 'ltr',
                        format: '',
                        indent: 0,
                        version: 1,
                        value: 4,
                      },
                    ],
                    direction: 'ltr',
                    format: '',
                    indent: 0,
                    listType: 'number',
                    start: 1,
                    tag: 'ol',
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                version: 1,
              },
            },
            size: 'full',
          },
        ],
      },
      {
        blockName: 'Required Documents',
        blockType: 'content',
        columns: [
          {
            richText: {
              root: {
                type: 'root',
                children: [
                  {
                    type: 'heading',
                    children: [
                      {
                        type: 'text',
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: 'Required Documents',
                        version: 1,
                      },
                    ],
                    direction: 'ltr',
                    format: '',
                    indent: 0,
                    tag: 'h2',
                    version: 1,
                  },
                  {
                    type: 'list',
                    children: [
                      {
                        type: 'listitem',
                        children: [
                          {
                            type: 'text',
                            detail: 0,
                            format: 0,
                            mode: 'normal',
                            style: '',
                            text: 'Completed application form',
                            version: 1,
                          },
                        ],
                        direction: 'ltr',
                        format: '',
                        indent: 0,
                        version: 1,
                        value: 1,
                      },
                      {
                        type: 'listitem',
                        children: [
                          {
                            type: 'text',
                            detail: 0,
                            format: 0,
                            mode: 'normal',
                            style: '',
                            text: 'Certified copies of academic transcripts',
                            version: 1,
                          },
                        ],
                        direction: 'ltr',
                        format: '',
                        indent: 0,
                        version: 1,
                        value: 2,
                      },
                      {
                        type: 'listitem',
                        children: [
                          {
                            type: 'text',
                            detail: 0,
                            format: 0,
                            mode: 'normal',
                            style: '',
                            text: 'Birth certificate',
                            version: 1,
                          },
                        ],
                        direction: 'ltr',
                        format: '',
                        indent: 0,
                        version: 1,
                        value: 3,
                      },
                      {
                        type: 'listitem',
                        children: [
                          {
                            type: 'text',
                            detail: 0,
                            format: 0,
                            mode: 'normal',
                            style: '',
                            text: 'National ID card or passport',
                            version: 1,
                          },
                        ],
                        direction: 'ltr',
                        format: '',
                        indent: 0,
                        version: 1,
                        value: 4,
                      },
                      {
                        type: 'listitem',
                        children: [
                          {
                            type: 'text',
                            detail: 0,
                            format: 0,
                            mode: 'normal',
                            style: '',
                            text: 'Passport-size photographs (4 copies)',
                            version: 1,
                          },
                        ],
                        direction: 'ltr',
                        format: '',
                        indent: 0,
                        version: 1,
                        value: 5,
                      },
                      {
                        type: 'listitem',
                        children: [
                          {
                            type: 'text',
                            detail: 0,
                            format: 0,
                            mode: 'normal',
                            style: '',
                            text: 'Medical certificate',
                            version: 1,
                          },
                        ],
                        direction: 'ltr',
                        format: '',
                        indent: 0,
                        version: 1,
                        value: 6,
                      },
                    ],
                    direction: 'ltr',
                    format: '',
                    indent: 0,
                    listType: 'bullet',
                    start: 1,
                    tag: 'ul',
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                version: 1,
              },
            },
            size: 'full',
          },
        ],
      },
      {
        blockName: 'Academic Calendar',
        blockType: 'content',
        columns: [
          {
            richText: {
              root: {
                type: 'root',
                children: [
                  {
                    type: 'heading',
                    children: [
                      {
                        type: 'text',
                        detail: 0,
                        format: 0,
                        mode: 'normal',
                        style: '',
                        text: 'Important Dates',
                        version: 1,
                      },
                    ],
                    direction: 'ltr',
                    format: '',
                    indent: 0,
                    tag: 'h2',
                    version: 1,
                  },
                  {
                    type: 'paragraph',
                    children: [
                      {
                        type: 'text',
                        detail: 0,
                        format: 1,
                        mode: 'normal',
                        style: '',
                        text: 'Academic Sessions:',
                        version: 1,
                      },
                    ],
                    direction: 'ltr',
                    format: '',
                    indent: 0,
                    textFormat: 0,
                    version: 1,
                  },
                  {
                    type: 'list',
                    children: [
                      {
                        type: 'listitem',
                        children: [
                          {
                            type: 'text',
                            detail: 0,
                            format: 1,
                            mode: 'normal',
                            style: '',
                            text: 'September Session: ',
                            version: 1,
                          },
                          {
                            type: 'text',
                            detail: 0,
                            format: 0,
                            mode: 'normal',
                            style: '',
                            text: 'Applications open in July, classes begin in September',
                            version: 1,
                          },
                        ],
                        direction: 'ltr',
                        format: '',
                        indent: 0,
                        version: 1,
                        value: 1,
                      },
                      {
                        type: 'listitem',
                        children: [
                          {
                            type: 'text',
                            detail: 0,
                            format: 1,
                            mode: 'normal',
                            style: '',
                            text: 'January Session: ',
                            version: 1,
                          },
                          {
                            type: 'text',
                            detail: 0,
                            format: 0,
                            mode: 'normal',
                            style: '',
                            text: 'Applications open in November, classes begin in January',
                            version: 1,
                          },
                        ],
                        direction: 'ltr',
                        format: '',
                        indent: 0,
                        version: 1,
                        value: 2,
                      },
                      {
                        type: 'listitem',
                        children: [
                          {
                            type: 'text',
                            detail: 0,
                            format: 1,
                            mode: 'normal',
                            style: '',
                            text: 'March Session: ',
                            version: 1,
                          },
                          {
                            type: 'text',
                            detail: 0,
                            format: 0,
                            mode: 'normal',
                            style: '',
                            text: 'Applications open in January, classes begin in March',
                            version: 1,
                          },
                        ],
                        direction: 'ltr',
                        format: '',
                        indent: 0,
                        version: 1,
                        value: 3,
                      },
                    ],
                    direction: 'ltr',
                    format: '',
                    indent: 0,
                    listType: 'bullet',
                    start: 1,
                    tag: 'ul',
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                version: 1,
              },
            },
            size: 'full',
          },
        ],
      },
      {
        blockName: 'Detailed Admissions Information',
        blockType: 'admissionsInfo',
        displayType: 'all-programs',
        showRequirements: true,
        showDeadlines: true,
        showFees: true,
        showApplicationSteps: true,
        layout: 'accordion',
      },
      {
        blockName: 'Academic Calendar',
        blockType: 'academicCalendar',
        showCurrentSemester: true,
        showUpcomingEvents: true,
        showExamSchedule: true,
        showHolidays: true,
        layout: 'detailed',
      },
      {
        blockName: 'Application Form',
        blockType: 'formBlock',
        form: applicationForm.id,
      },
      {
        blockName: 'Contact Admissions',
        blockType: 'cta',
        links: [
          {
            link: {
              type: 'custom',
              appearance: 'default',
              label: 'Call Admissions Office',
              url: 'tel:+237233332334',
            },
          },
          {
            link: {
              type: 'custom',
              appearance: 'outline',
              label: 'Email Us',
              url: 'mailto:admissions@sduinstitute.com',
            },
          },
        ],
        richText: {
          root: {
            type: 'root',
            children: [
              {
                type: 'heading',
                children: [
                  {
                    type: 'text',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: 'Need Help with Your Application?',
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                tag: 'h2',
                version: 1,
              },
              {
                type: 'paragraph',
                children: [
                  {
                    type: 'text',
                    detail: 0,
                    format: 0,
                    mode: 'normal',
                    style: '',
                    text: 'Our admissions team is here to help you every step of the way. Contact us for personalized guidance and support.',
                    version: 1,
                  },
                ],
                direction: 'ltr',
                format: '',
                indent: 0,
                textFormat: 0,
                version: 1,
              },
            ],
            direction: 'ltr',
            format: '',
            indent: 0,
            version: 1,
          },
        },
      },
    ],
    meta: {
      description: 'Apply to SDU Institute - Learn about admission requirements, application process, required documents, and important dates for our nursing and biomedical sciences programs.',
      image: metaImage.id,
      title: 'Admissions - SDU Institute',
    },
    title: 'Admissions',
  }
}