import type { RequiredDataFromCollectionSlug } from 'payload'

export const applicationForm: RequiredDataFromCollectionSlug<'forms'> = {
  title: 'Online Application Form',
  confirmationMessage: {
    root: {
      type: 'root',
      children: [
        {
          type: 'heading',
          children: [
            {
              type: 'text',
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: 'Thank you for your application! We will contact you soon.',
              version: 1,
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          tag: 'h2',
          version: 1,
        },
      ],
      direction: 'ltr',
      format: '',
      indent: 0,
      version: 1,
    },
  },
  confirmationType: 'message',
  createdAt: '2023-01-12T21:47:41.374Z',
  emails: [
    {
      emailFrom: '"SDU Institute" <admissions@sduinstitute.com>',
      emailTo: '{{email}}',
      message: {
        root: {
          type: 'root',
          children: [
            {
              type: 'paragraph',
              children: [
                {
                  type: 'text',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'Your application has been received successfully.',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              version: 1,
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          version: 1,
        },
      },
      subject: "You've received a new application.",
    },
  ],
  fields: [
    {
      name: 'fullName',
      blockName: 'fullName',
      blockType: 'text',
      label: 'Full Name',
      required: true,
      width: 100,
    },
    {
      name: 'email',
      blockName: 'email',
      blockType: 'email',
      label: 'Email Address',
      required: true,
      width: 100,
    },
    {
      name: 'phone',
      blockName: 'phone',
      blockType: 'text',
      label: 'Phone Number',
      required: true,
      width: 100,
    },
    {
      name: 'program',
      blockName: 'program',
      blockType: 'select',
      label: 'Program of Interest',
      required: true,
      width: 100,
      options: [
        { label: 'HND Nursing', value: 'hnd-nursing' },
        { label: 'HND Laboratory Technology', value: 'hnd-lab-tech' },
        { label: 'HND Biomedical Sciences', value: 'hnd-biomedical' },
        { label: 'HND Secretarial Medical', value: 'hnd-secretarial' },
        { label: 'BTS Nursing', value: 'bts-nursing' },
        { label: 'BTS Laboratory Technology', value: 'bts-lab-tech' },
        { label: 'BTS Midwifery', value: 'bts-midwifery' },
      ],
    },
    {
      name: 'campus',
      blockName: 'campus',
      blockType: 'select',
      label: 'Preferred Campus',
      required: true,
      width: 100,
      options: [
        { label: 'Limbé Campus', value: 'limbe' },
        { label: 'Douala Campus', value: 'douala' },
        { label: 'Yaoundé Campus', value: 'yaounde' },
      ],
    },
    {
      name: 'previousEducation',
      blockName: 'previousEducation',
      blockType: 'textarea',
      label: 'Previous Education',
      required: true,
      width: 100,
    },
    {
      name: 'message',
      blockName: 'message',
      blockType: 'textarea',
      label: 'Additional Information',
      required: false,
      width: 100,
    },
  ],
  redirect: undefined,
  submitButtonLabel: 'Submit Application',
  updatedAt: '2023-01-12T21:47:41.374Z',
}