import type { RequiredDataFromCollectionSlug } from 'payload'

export const campusVisitForm: RequiredDataFromCollectionSlug<'forms'> = {
  title: 'Schedule a Campus Visit',
  confirmationMessage: {
    root: {
      type: 'root',
      children: [
        {
          type: 'heading',
          children: [
            {
              type: 'text',
              detail: 0,
              format: 0,
              mode: 'normal',
              style: '',
              text: 'Thank you! We will contact you within 24 hours to confirm your campus visit.',
              version: 1,
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          tag: 'h2',
          version: 1,
        },
      ],
      direction: 'ltr',
      format: '',
      indent: 0,
      version: 1,
    },
  },
  confirmationType: 'message',
  emails: [
    {
      emailFrom: '"SDU Institute" <info@sduinstitute.com>',
      emailTo: '{{email}}',
      message: {
        root: {
          type: 'root',
          children: [
            {
              type: 'paragraph',
              children: [
                {
                  type: 'text',
                  detail: 0,
                  format: 0,
                  mode: 'normal',
                  style: '',
                  text: 'Your campus visit request has been received successfully.',
                  version: 1,
                },
              ],
              direction: 'ltr',
              format: '',
              indent: 0,
              textFormat: 0,
              version: 1,
            },
          ],
          direction: 'ltr',
          format: '',
          indent: 0,
          version: 1,
        },
      },
      subject: "You've received a new campus visit request.",
    },
  ],
  fields: [
    {
      name: 'fullName',
      blockName: 'fullName',
      blockType: 'text',
      label: 'Full Name',
      required: true,
      width: 100,
    },
    {
      name: 'email',
      blockName: 'email',
      blockType: 'email',
      label: 'Email Address',
      required: true,
      width: 100,
    },
    {
      name: 'phone',
      blockName: 'phone',
      blockType: 'text',
      label: 'Phone Number',
      required: true,
      width: 100,
    },
    {
      name: 'campus',
      blockName: 'campus',
      blockType: 'select',
      label: 'Campus to Visit',
      required: true,
      width: 100,
      options: [
        { label: 'Douala Campus (Main)', value: 'douala' },
        { label: 'Yaoundé Campus', value: 'yaounde' },
        { label: 'Limbé Campus', value: 'limbe' },
        { label: 'Buea Campus', value: 'buea' },
      ],
    },
    {
      name: 'visitDate',
      blockName: 'visitDate',
      blockType: 'text',
      label: 'Preferred Visit Date',
      required: true,
      width: 100,
    },
    {
      name: 'visitTime',
      blockName: 'visitTime',
      blockType: 'select',
      label: 'Preferred Time',
      required: true,
      width: 100,
      options: [
        { label: '9:00 AM - 11:00 AM', value: 'morning' },
        { label: '11:00 AM - 1:00 PM', value: 'midday' },
        { label: '2:00 PM - 4:00 PM', value: 'afternoon' },
      ],
    },
    {
      name: 'interests',
      blockName: 'interests',
      blockType: 'textarea',
      label: 'Areas of Interest',
      required: false,
      width: 100,
    },
    {
      name: 'additionalInfo',
      blockName: 'additionalInfo',
      blockType: 'textarea',
      label: 'Additional Information',
      required: false,
      width: 100,
    },
  ],
  redirect: undefined,
  submitButtonLabel: 'Schedule Visit',
}