import {
  MdHome,
  MdInfo,
  MdEmail,
  MdPhone,
  MdLocationOn,
  MdArrowForward,
  MdArrowBack,
  MdDownload,
  MdUpload,
  MdShare,
  MdFavorite,
  MdStar,
  MdSearch,
  MdMenu,
  MdClose,
  MdAdd,
  MdRemove,
  MdEdit,
  MdDelete,
  MdSave,
  MdCancel,
  MdCheck,
  MdWarning,
  MdError,
  MdNotifications,
  MdSettings,
  MdShoppingCart,
  MdPayment,
  MdSecurity,
  MdVisibility,
  MdVisibilityOff,
  MdHelp,
  MdSupport,
  MdFeedback,
  MdBusiness,
  MdWork,
  MdSchool,
  MdEvent,
  MdCalendarToday,
  MdAccessTime,
  MdLanguage,
  MdPublic,
  MdLock,
  MdLockOpen,
  MdRefresh,
  MdSync,
  MdCloudDownload,
  MdCloudUpload,
  MdPrint,
  MdFileDownload,
  MdFileUpload,
  MdAttachFile,
  MdLink,
  MdLaunch,
  MdOpenInNew,
  MdExpandMore,
  MdExpandLess,
  MdChevronLeft,
  MdChevronRight,
  MdKeyboardArrowUp,
  MdKeyboardArrowDown,
  MdKeyboardArrowLeft,
  MdKeyboardArrowRight,
  MdPerson,
  MdOutlineTv,
  MdOutlineTurnedInNot,
  MdOutlineTurnedIn,
} from 'react-icons/md'

export type MaterialIconName = keyof typeof materialIcons

export const materialIcons = {
  MdHome,
  MdInfo,
  MdEmail,
  MdPhone,
  MdLocationOn,
  MdArrowForward,
  MdArrowBack,
  MdDownload,
  MdUpload,
  MdShare,
  MdFavorite,
  MdStar,
  MdSearch,
  MdMenu,
  MdClose,
  MdAdd,
  MdRemove,
  MdEdit,
  MdDelete,
  MdSave,
  MdCancel,
  MdCheck,
  MdWarning,
  MdError,
  MdNotifications,
  MdSettings,
  MdShoppingCart,
  MdPayment,
  MdSecurity,
  MdVisibility,
  MdVisibilityOff,
  MdHelp,
  MdSupport,
  MdFeedback,
  MdBusiness,
  MdWork,
  MdSchool,
  MdEvent,
  MdCalendarToday,
  MdAccessTime,
  MdLanguage,
  MdPublic,
  MdLock,
  MdLockOpen,
  MdRefresh,
  MdSync,
  MdCloudDownload,
  MdCloudUpload,
  MdPrint,
  MdFileDownload,
  MdFileUpload,
  MdAttachFile,
  MdLink,
  MdLaunch,
  MdOpenInNew,
  MdExpandMore,
  MdExpandLess,
  MdChevronLeft,
  MdChevronRight,
  MdKeyboardArrowUp,
  MdKeyboardArrowDown,
  MdKeyboardArrowLeft,
  MdKeyboardArrowRight,
  MdPerson,
  MdOutlineTv,
  MdOutlineTurnedInNot,
  MdOutlineTurnedIn,
}

export const materialIconOptions = [
  { label: 'None', value: '' },
  { label: 'Home', value: 'MdHome' },
  { label: 'Info', value: 'MdInfo' },
  { label: 'Email', value: 'MdEmail' },
  { label: 'Phone', value: 'MdPhone' },
  { label: 'Location', value: 'MdLocationOn' },
  { label: 'Arrow Forward', value: 'MdArrowForward' },
  { label: 'Arrow Back', value: 'MdArrowBack' },
  { label: 'Download', value: 'MdDownload' },
  { label: 'Upload', value: 'MdUpload' },
  { label: 'Share', value: 'MdShare' },
  { label: 'Favorite', value: 'MdFavorite' },
  { label: 'Star', value: 'MdStar' },
  { label: 'Search', value: 'MdSearch' },
  { label: 'Menu', value: 'MdMenu' },
  { label: 'Close', value: 'MdClose' },
  { label: 'Add', value: 'MdAdd' },
  { label: 'Remove', value: 'MdRemove' },
  { label: 'Edit', value: 'MdEdit' },
  { label: 'Delete', value: 'MdDelete' },
  { label: 'Save', value: 'MdSave' },
  { label: 'Cancel', value: 'MdCancel' },
  { label: 'Check', value: 'MdCheck' },
  { label: 'Warning', value: 'MdWarning' },
  { label: 'Error', value: 'MdError' },
  { label: 'Notifications', value: 'MdNotifications' },
  { label: 'Settings', value: 'MdSettings' },
  { label: 'Shopping Cart', value: 'MdShoppingCart' },
  { label: 'Payment', value: 'MdPayment' },
  { label: 'Security', value: 'MdSecurity' },
  { label: 'Visibility', value: 'MdVisibility' },
  { label: 'Visibility Off', value: 'MdVisibilityOff' },
  { label: 'Help', value: 'MdHelp' },
  { label: 'Support', value: 'MdSupport' },
  { label: 'Feedback', value: 'MdFeedback' },
  { label: 'Business', value: 'MdBusiness' },
  { label: 'Work', value: 'MdWork' },
  { label: 'School', value: 'MdSchool' },
  { label: 'Event', value: 'MdEvent' },
  { label: 'Calendar', value: 'MdCalendarToday' },
  { label: 'Time', value: 'MdAccessTime' },
  { label: 'Language', value: 'MdLanguage' },
  { label: 'Public', value: 'MdPublic' },
  { label: 'Lock', value: 'MdLock' },
  { label: 'Lock Open', value: 'MdLockOpen' },
  { label: 'Refresh', value: 'MdRefresh' },
  { label: 'Sync', value: 'MdSync' },
  { label: 'Cloud Download', value: 'MdCloudDownload' },
  { label: 'Cloud Upload', value: 'MdCloudUpload' },
  { label: 'Print', value: 'MdPrint' },
  { label: 'File Download', value: 'MdFileDownload' },
  { label: 'File Upload', value: 'MdFileUpload' },
  { label: 'Attach File', value: 'MdAttachFile' },
  { label: 'Link', value: 'MdLink' },
  { label: 'Launch', value: 'MdLaunch' },
  { label: 'Open in New', value: 'MdOpenInNew' },
  { label: 'Expand More', value: 'MdExpandMore' },
  { label: 'Expand Less', value: 'MdExpandLess' },
  { label: 'Chevron Left', value: 'MdChevronLeft' },
  { label: 'Chevron Right', value: 'MdChevronRight' },
  { label: 'Arrow Up', value: 'MdKeyboardArrowUp' },
  { label: 'Arrow Down', value: 'MdKeyboardArrowDown' },
  { label: 'Arrow Left', value: 'MdKeyboardArrowLeft' },
  { label: 'Arrow Right', value: 'MdKeyboardArrowRight' },
  { label: 'Person', value: 'MdPerson' },
  { label: 'TV', value: 'MdOutlineTv' },
  { label: 'Turned In Not', value: 'MdOutlineTurnedInNot' },
  { label: 'Turned In', value: 'MdOutlineTurnedIn' },
]

export const iconPlacementOptions = [
  { label: 'Right', value: 'right' },
  { label: 'Left', value: 'left' },
]
